# Конфигурация балансировщика нагрузки
loadBalancer:
  method: WeightedRoundRobin
  params:
    healthCheckInterval: 10s

# Список бэкендов
backends:
  - id: backend1
    url: http://localhost:8081
    weight: 2.0
    connectTimeout: 5s
    readTimeout: 10s
    maxConnections: 100

  - id: backend2
    url: http://localhost:8082
    weight: 1.0
    connectTimeout: 5s
    readTimeout: 10s
    maxConnections: 100

# Настройки rate limiter
rateLimiter:
  enabled: true
  type: TokenBucket
  tokenBucket:
    rate: 100  # запросов в секунду по умолчанию
    burst: 200 # максимальный размер корзины

logger:
  logLevel: "info"
  nodeIP: "10.0.0.1"
  podIP: "10.0.1.1"
  serviceName: "load-balancer"   
